### ISSUE TITLE
Compass:::simpleCOMPASS ->  Posterior() function

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/COMPASS#48]
Dear Dr. Greg Finak
I appreciate your recent help. 
I post my issue here. 

cd4 <- read.xlsx2("cd4_inter.xls", sheetIndex = 1)
cd4u3 <- U3 <- subset(cd4, (cd4$Stimulation == "Contol") & (cd4$Day == 3)); nrow(U3) # 70
cd4g3 <- G3 <- subset(cd4, (cd4$Stimulation == "Sample") & (cd4$Day == 3)); nrow(G3) # 70

fit2 <-  COMPASS:::SimpleCOMPASS(data.matrix(cd4u3[,-c(1:6)]), data.matrix(cd4g3[,-c(1:6)]), meta, "iid", "sid", iterations=100, verbose = TRUE)     # 20 second running time

post2 <- Posterior(fit2) ; post2 # NULL
plot(fit2) # working well

I think I don't know how to use "Posterior()" well. 
Sim-data is working well at "Posterior" function, however my simpleCOMPASS output, "fit2", is not. 
> fit      # Sim-data output
A COMPASS model fit on 10 paired samples.
> fit2     # my Compass:::simpleCOMPASS output
A COMPASS model fit on 70 paired samples.  
One of my guess is that it has too many paired samples. Is it right ?

Any help would be appreciated. 
Sincerely, 
Dohoon

**Comment by kdh4win4** [comment]
Sample      ID Visit Stimulation  Group Vaccine V1&V2&V3&V4&V5&V6          V1&V2&V3&V4&V5&!V6
B01009.fcs      d30     3     _Unstim   G1          Active                       0                                 0
B01007.fcs      d30     3     _Unstim   G1          Active                       0                                 0

**Comment by gfinak** [comment]
I'll be in the office Monday. In the meantime, increase the number of
iterations to at least 40000 and 8 replications.

I'd need to see the structure of your data to give more concrete advice.

Greg Finak

**Comment by ssuthram-gilead** [comment]
Was this issue resolved? I am getting the same error
