### ISSUE TITLE
ShinyCOMPASS cannot find "transform_subset_label"?

### ISSUE THREAD

**Issue by zhanxw** [RGLab/COMPASS#51]
Where to find the definition of function "transform_subset_label"
Here is the error log:

<pre>
> shinyCOMPASS(fit)
Preparing data for the Shiny application, please wait a moment...
The files necessary for launching the COMPASS Shiny application have been copied to '/var/folders/13/r18ls6xn1llg31h11b4lybh80000gn/T//RtmpTGPJIz/shinyCOMPASS'.
Starting the Shiny application...

Listening on http://127.0.0.1:6281
Warning: Error in unname: could not find function "transform_subset_label"
Stack trace (innermost first):
    42: unname
    41: rev
     2: runApp
     1: shinyCOMPASS
Error in unname(transform_subset_label(colnames(DATA$data$n_s)[-ncol(DATA$data$n_s)])) : 
  could not find function "transform_subset_label"
</pre>

**Comment by gfinak** [comment]
Seems that there was a call to the function in ui.R, but ui.R was not sourcing the common_function.R file. I'll push a fix.

**Comment by zhanxw** [comment]
Thanks.

I used this version, and after changing this line from:
 
    shinyCOMPASS(fit, stimulated="Treatment", unstimulated="Control")

to:

    shinyCOMPASS(fit)


I can make shinyCOMPASS work now. Thanks.
