### ISSUE TITLE
order_by_max_functionality in plotCOMPASSResult

### ISSUE THREAD

**Issue by demorrisfhcrc** [RGLab/COMPASS#52]
I thought this had been fixed, but seemingly it is still not working. 

I want to turn re-ordering of columns OFF in the COMPASS heatmaps.  There is an argument both in plotCOMPASSResult and in pheatmap which should accomplish this.... order_by_max_functionality.

If I set that to FALSE, it still is re-ordering.

If I'm looking at the correct code, I think I see the problem.  That argument is handled in plotCOMPASSResult, but FALSE also needs to be passed to pheatmap (since that argument defaults to TRUE).

**Comment by gfinak** [comment]
Excellent, I’ll have a look and push a fix.


Greg Finak
Senior Staff Scientist
Department of Biostatistics, Bioinformatics, and Epidemiology
Vaccine and Infectious Disease Division
206.667.3116
gfinak at fredhutch.org

**Comment by gfinak** [comment]
Hmm...It's passed in the ellipsis in the call to pheatmap, it should be treated properly.

**Comment by gfinak** [comment]
I've pushed a fix, give it a go.

**Comment by demorrisfhcrc** [comment]
install_github trunk? or from Bioconductor?

I was about to write that the ellipsis isn't passed on when the argument is handled.

**Comment by gfinak** [comment]
Trunk

**Comment by demorrisfhcrc** [comment]
I clicked on the code link to see what the fix was… and noticed it’s missing a “y”.

**Comment by gfinak** [comment]
sorted in   1df984b
