### ISSUE TITLE
The statistical methods used in COMPASS:::SimpleCOMPASS 

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/COMPASS#63]
Hi Dr. Greg FInak, 

Can I know where I can see the statistical method coding in COMPASS:::SimpleCOMPASS ?
I want to know how functionality scores are calculated.
Thank you.

**Comment by gfinak** [comment]
SimpleCompass just calls the same internals as COMPASS, so everything is calculated the same way.

If you're finding discrepancies, you probably have an issue with your input data formatting. SimpleCOMPASS does minimal checking compared to the COMPASS method so it's easier to unintentionally enter data that's not formatted properly, and the method won't really complain.

Just follow the function calls in the source code.

**Comment by kdh4win4** [comment]
Hi, Dr. Finak,
I found key function code for COMPASS-discrete and reading it now. 
I compared samples like this;
At visit 2nd, Stim(HIV-vaccine#1) vs Control group(DMSO).
It has 8 placebo and 16 vaccine samples.
I think the result is fine. functionality score table is pretty reasonable. 
How do you think about that?
<img width="460" alt="screen shot 2018-12-11 at 3 01 30 pm" src="https://user-images.githubusercontent.com/12645005/49826747-b1b0c680-fd55-11e8-8221-a47d7bb96017.png">
?
Thank you very much, Greg.

**Comment by kdh4win4** [comment]
v1  = visit 1st
v2  = visit 2nd
v3  = visit 3rd
First placebo sample is somewhat different, however, I think that is just fine considering whole functionality scores.

**Comment by gfinak** [comment]
Looks pretty reasonable. Do you know why you have `NA`s?
You could always look at the raw data for that "outlier" placebo at v3 to confirm it's real.

**Comment by gfinak** [comment]
I would add that if visit 1 is pre-vx or really a very early time point there may not be any memory T cell response yet.

**Comment by kdh4win4** [comment]
NA is due to the loss of the specific donor value, the original excel file which they gave me, did not have the value. That is the reason. 
I also think this functionality score result is pretty reasonable. 
Thank you very much for confirming it.

**Comment by kdh4win4** [comment]
Definitely, pre-vx has probably no T cell response at that time. 
Thank you very much, Greg.
