### ISSUE TITLE
Question : COMPASS-discrete

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/COMPASS#65]
Dear Dr. Greg Finak, 
Can I know what below functions in **COMPASS-discrete.R** mean ?
res1 <- .Call(C_updategammak_noPu
res3 <- .Call(C_updatealphas_Exp
res2 <- .Call(C_updatealphau_noPu_Exp,
res1 <- .Call(C_updategammak_noPu
Thank you for your time?

**Comment by gfinak** [comment]
These call out to compiled code that update the various model parameters conditional on the others.

**Comment by kdh4win4** [comment]
Where does the "C_updategammak_noPu" come from?

**Comment by gfinak** [comment]
It's a function in the C source code of the package.

**Comment by kdh4win4** [comment]
Can I see the C source code? Or I am not allowed?

**Comment by gfinak** [comment]
it's in the src directory of the package.

**Comment by kdh4win4** [comment]
Thank you very much, Dr. Greg Finak
