### ISSUE TITLE
Different sample number at each time point

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/COMPASS#66]
Dear Dr. Greg Finak, 
![screen shot 2018-12-14 at 10 52 42 am](https://user-images.githubusercontent.com/12645005/50013190-806f0b00-ff8e-11e8-8728-9848f925608c.png)
Each column has Functionality scores of Stim1_vs_Control at each time point.
There are five different time points.
Visit 1st, 2nd, 3rd, 4th, and 5th
The issue is each time point has different sample number
The sample numbers are 25,24,25,48, and 47
Is it acceptable or nonsense to you?
Thank you for your time

**Comment by gfinak** [comment]
@kdh4win4 I don't entirely understand the issue. In the table you pasted I can't see the donor Id or any sample number identifier. Are you asking how to label samples for COMPASS analysis when you have multiple timepoints?

**Comment by kdh4win4** [comment]
![screen shot 2018-12-14 at 11 46 04 am](https://user-images.githubusercontent.com/12645005/50015953-dc895d80-ff95-11e8-8683-2eb06594e128.png)

**Comment by kdh4win4** [comment]
Here is donor ID.

**Comment by kdh4win4** [comment]
The first column has all NA or zero values. 
I checked the original excel file(boolean), there are very few cells in each Stim and Control groups.
I think that is the reason for this situation.
Would you let me know what you think about that?
Thank you for your time.

**Comment by gfinak** [comment]
Just to be clear, you've run COMPASS 5 times, once for each column?
Or did you assign a unique sample id to each of the five visit (columns) and run COMPASS once?
If  I were you I would look at one of the subjects and timepoints where you get an NA, and look at all the cell subsets you're feeding into the model. 
What does the mean_gamma matrix look like (these are the averaged monte carlo samples from the model), 
what does the gamma matrix look like (these are the individual monte carlo samples). NAs in these matices can give you hints as to which cell subset is causing problems (if any). And then based on that go back and look at the input cell counts for those cell subsets.

**Comment by kdh4win4** [comment]
Once for each column. 

NA is caused by missing values. 
For example, Placebo:6123 sample has only v4(visit 4th) and v5(visit 5th)   HIV(stim) and DMSO(control) values. 
I am sorry for confusing you. 
Thank you for your time, Dr. Finak.
