### ISSUE TITLE
Mislabeling and Functionality scores

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/COMPASS#68]
Are functional and multifunctional scores affected by other sample values?
For example, I labeled some placebo samples into vaccine samples, some vaccine samples into placebos by mistake.
I saw the mislabelling affected the functionality scores.
Comparing values ​​before and after I saw several different functionality and polyfunctionality scores.

**Comment by gfinak** [comment]
Yes, mislabelling will affect the scores of other samples. COMPASS is a Bayesian model so information is shared across subjects through shared hyperparameters.  Incorrect labeling of samples will impact the response probabilities of other samples by changing the overall distribution of magnitudes of stimulated and non stimulated samples.

**Comment by kdh4win4** [comment]
That's what I want to confirm !.
Thank you very much, Dr. Greg Finak
