### ISSUE TITLE
Repeatability

### ISSUE THREAD

**Issue by kdh4win4** [RGLab/COMPASS#69]
If someone continue to analyze with the same data multiple times, is it possible to get a slightly different values because of Bayesian or Markov chain Monte Carlo algorithm?

**Comment by gfinak** [comment]
Yes the results are subject to stochastic variation due to the mcmc sampler. You need to call set.seed() with a fixed value before running simplecompass.

**Comment by kdh4win4** [comment]
Thank you, Dr. Finak
